// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig(): Promise<string>;

export function GetDeviceInfo(): Promise<{[key: string]: any}>;

export function GetPeers(): Promise<string>;

export function GetServerURL(): Promise<string>;

export function GetTransfers(): Promise<string>;

export function SetDeviceName(arg1: string): Promise<void>;