// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDeviceInfo() {
  return window['go']['main']['App']['GetDeviceInfo']();
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function GetTransfers() {
  return window['go']['main']['App']['GetTransfers']();
}

export function SetDeviceName(arg1) {
  return window['go']['main']['App']['SetDeviceName'](arg1);
}